//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

# Configuration for Java SE and EE

## Status

The content of this repository is OUTDATED!

Please go to the Apache Geronimo Config project for further information.

$> svn co https://svn.apache.org/repos/asf/geronimo/components/config/trunk

== History

This repository contains the original MicroProfile Config proposal and a Config JSR proposal based on the concepts Gerhard and I created in Apache OpenWebBeans, CODI and DeltaSpike.
See the separate branches for more info.

== The Config API

The API later got moved to the MicroProfile repository which itself later moved under the Eclipse umbrella.
It now can be found at

https://github.com/eclipse/microprofile-config/


== The Config IMPL

The implementation of MicroProfile Config can be found at the Apache Geronimo Project.

$> svn co https://svn.apache.org/repos/asf/geronimo/components/config/trunk
 
